### ISSUE TITLE
プレイヤー

### ISSUE THREAD

**Issue by colomeru** [OnlineGameRiceCake2017/DevelopRepository#4]
- 描画

- 移動

- スタミナ

- 回転

- 攻撃

- 被弾

- 死亡

- アニメーション

**Comment by shitensyo** [comment]
移動およびスタミナの計算、攻撃、被弾まで完了

**Comment by hayashi0221** [comment]
一通りのアニメーションの追加が完了
キーを押すとモーションの確認ができます。

**Comment by colomeru** [comment]
モデルの関係上アニメーションは無し
完成
